global:
  scrape_interval:     15s
  evaluation_interval: 15s
 
alerting:
  alertmanagers:
  - static_configs:
      - targets: ['172.31.43.176:9093']
rule_files:
  - "rules/*.yml"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['172.31.43.176:9090']
        labels:
          instance: prometheus
 
  - job_name: node
    static_configs:
      - targets: ['172.31.43.176:9100']

  - job_name: mysql
    static_configs:
      - targets: ['172.31.43.176:9104']

  - job_name: redis
    static_configs:
      - targets: ['172.31.43.176:9121']

  - job_name: mongodb
    static_configs:
      - targets: ['172.31.43.176:9216']

  - job_name: kafka
    static_configs:
      - targets: ['172.31.43.176:9308']

  - job_name: pushgateway
    static_configs:
      - targets: ['172.31.43.176:9091']

  - job_name: php-fpm
    static_configs:
      - targets: ['172.31.43.176:9253']